spring:
  application:
    name: CRM-PROCESS
server:
  port: 9898
logging:
  file: logs/crm.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"